/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#4cd7f6",
        "surface-tint": "#00687a",
        "tertiary": "#0053db",
        "error-container": "#ffdad6",
        "surface-container-highest": "#d3e4fe",
        "inverse-on-surface": "#eaf1ff",
        "surface-container-low": "#eff4ff",
        "primary-fixed": "#acedff",
        "tertiary-container": "#85a3ff",
        "secondary-fixed-dim": "#b5c7ea",
        "on-primary-fixed": "#001f26",
        "tertiary-fixed": "#dbe1ff",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-tertiary-container": "#003490",
        "primary-fixed-dim": "#4cd7f6",
        "background": "#f8f9ff",
        "secondary-container": "#c8dbfe",
        "surface-container": "#e5eeff",
        "on-error": "#ffffff",
        "inverse-surface": "#213145",
        "surface-container-lowest": "#ffffff",
        "on-background": "#0b1c30",
        "on-tertiary-fixed": "#00174b",
        "on-surface": "#0b1c30",
        "on-primary-fixed-variant": "#004e5c",
        "secondary": "#4d5f7d",
        "primary-container": "#06b6d4",
        "surface-dim": "#cbdbf5",
        "on-secondary": "#ffffff",
        "primary": "#00687a",
        "surface-bright": "#f8f9ff",
        "outline-variant": "#bcc9cd",
        "on-secondary-fixed-variant": "#354764",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#003ea8",
        "on-tertiary": "#ffffff",
        "outline": "#6d797d",
        "on-secondary-container": "#4e607e",
        "surface-container-high": "#dce9ff",
        "error": "#ba1a1a",
        "surface-variant": "#d3e4fe",
        "on-surface-variant": "#3d494c",
        "secondary-fixed": "#d5e3ff",
        "surface": "#f8f9ff",
        "on-error-container": "#93000a",
        "on-primary-container": "#00424f",
        "on-secondary-fixed": "#061c36"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "margin-desktop": "1.5rem",
        "gutter-desktop": "1.5rem",
        "gutter": "1rem",
        "space-sm": "0.5rem",
        "space-xl": "1.5rem",
        "margin": "1rem",
        "space-2xl": "2rem",
        "space-2xs": "0.125rem",
        "space-md": "0.75rem",
        "space-xs": "0.25rem",
        "space-lg": "1rem"
      },
      fontFamily: {
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "metric-readout-lg": ["JetBrains Mono", "monospace"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "metric-readout-md": ["JetBrains Mono", "monospace"],
        "label-caps": ["JetBrains Mono", "monospace"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-xl-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "metric-readout-lg": ["28px", { lineHeight: "32px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "data-mono": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "title-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "headline-xl": ["36px", { lineHeight: "44px", fontWeight: "700" }],
        "metric-readout-md": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "label-caps": ["11px", { lineHeight: "14px", letterSpacing: "0.06em", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
